### ISSUE TITLE
Add total number of days in nepali month

### ISSUE THREAD

**Issue by subashadhi** [techgaun/ad-bs-converter#3]
Great job man on creating the package. 👍 

Can you add ` totaldays: calendar_data[bs_date.year][bs_date.month-1]` to the dateObj in offsetBSDays function so that we can also find the total number of days in the month? This in my view will be useful in a number of different scenarios.

**Comment by techgaun** [comment]
@subash95 how does above pull request look like?

**Comment by subashadhi** [comment]
@techgaun  perfect! Has this also been synced with the npm package?

**Comment by techgaun** [comment]
@subash95 I've not. Was waiting to see what you think of it. Am gonna publish it now

**Comment by techgaun** [comment]
@subash95 published

**Comment by subashadhi** [comment]
Thanks.
